// This file is auto-generated by scripts/generate-examples-index.js
// Do not edit this file manually
// Run "npm run generate:examples" to regenerate

export const v5_x_x_core_interpolation_BasicExample = `import React from 'react';
import { useValue, animate, withSpring } from 'react-ui-animate';
import '../../styles.css';

export default function App() {
  const [x, setX] = useValue(0);

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() => setX(withSpring(200))}
      >
        Animate
      </button>

      <animate.div
        style={{
          marginTop: 20,
          width: 100,
          height: 100,
          background: x.to([0, 200], ['teal', 'red']),
          translateX: x,
          borderRadius: 8,
        }}
      />
    </div>
  );
}
`;

export const v5_x_x_core_mount_BasicExample = `import React from 'react';
import { animate, Mount } from 'react-ui-animate';

const App = () => {
  const [open, setOpen] = React.useState(true);

  return (
    <>
      <Mount state={open}>
        {(animation) => (
          <animate.div
            style={{
              width: 100,
              height: 100,
              backgroundColor: 'teal',
              opacity: animation,
              borderRadius: 4,
              marginBottom: 10,
            }}
          />
        )}
      </Mount>

      <button
        onClick={() => {
          setOpen((prev) => !prev);
        }}
      >
        ANIMATE
      </button>
    </>
  );
};

export default App;
`;

export const v5_x_x_core_mount_MultiValuedExample = `import React from 'react';
import {
  animate,
  withSequence,
  withTiming,
  withSpring,
  Mount,
} from 'react-ui-animate';

const App = () => {
  const [open, setOpen] = React.useState(true);

  return (
    <>
      <Mount
        state={open}
        from={{ width: 200, opacity: 0, translateX: 0, rotate: 0 }}
        enter={withSequence([
          withTiming({ translateX: 100, opacity: 1, rotate: 0 }),
          withSpring({ width: 300 }),
        ])}
        exit={withSpring({
          translateX: 0,
          width: 200,
        })}
      >
        {({ width, opacity, translateX, rotate }) => (
          <animate.div
            style={{
              width: width,
              opacity,
              translateX,
              height: 100,
              backgroundColor: 'teal',
              rotate,
              borderRadius: 4,
              marginBottom: 10,
            }}
          />
        )}
      </Mount>

      <button
        onClick={() => {
          setOpen((prev) => !prev);
        }}
      >
        ANIMATE ME
      </button>
    </>
  );
};

export default App;
`;

export const v5_x_x_gesture_useDrag_BasicSetup = `import React, { useRef } from 'react';
import { animate, useDrag, useValue, withSpring } from 'react-ui-animate';

const App = () => {
  const ref = useRef<HTMLDivElement>(null);
  const [translateX, setTranslateX] = useValue(0);
  const [translateY, setTranslateY] = useValue(0);

  useDrag(ref, ({ down, movement }) => {
    setTranslateX(down ? movement.x : withSpring(0));
    setTranslateY(down ? movement.y : withSpring(0));
  });

  return (
    <animate.div
      ref={ref}
      style={{
        cursor: 'grab',
        translateX,
        translateY,
        width: 100,
        height: 100,
        backgroundColor: 'teal',
        borderRadius: 4,
      }}
    />
  );
};

export default App;
`;

export const v5_x_x_gesture_useDrag_MultipleElements = `import React, { createRef, useMemo, useRef } from 'react';
import { animate, useValue, useDrag, withSpring } from 'react-ui-animate';

const App = () => {
  const items = useRef(Array.from({ length: 5 }, () => 0));
  const [positions, setPositions] = useValue(items.current);

  const refs = useMemo(
    () => Array.from({ length: 3 }, () => createRef<HTMLDivElement>()),
    []
  );

  useDrag(refs, function ({ down, movement, index }) {
    if (down) {
      const newPositions = [...items.current];
      newPositions[index] = movement.x;
      setPositions(newPositions);
    } else {
      setPositions(withSpring(items.current));
    }
  });

  return (
    <>
      {refs.map((r, i) => (
        <animate.div
          key={i}
          ref={r}
          style={{
            width: 100,
            height: 100,
            cursor: 'grab',
            backgroundColor: 'teal',
            borderRadius: 4,
            marginBottom: 10,
            translateX: positions[i],
          }}
        />
      ))}
    </>
  );
};

export default App;
`;

export const v5_x_x_gesture_useMove_BasicSetup = `import React from 'react';
import { animate, useValue, useMove } from 'react-ui-animate';

const App = () => {
  const [pos, setPos] = useValue({ x: 0, y: 0 });

  useMove(window, function ({ event }) {
    setPos({ x: event.clientX, y: event.clientY });
  });

  return (
    <animate.div
      style={{
        width: 50,
        height: 50,
        backgroundColor: 'teal',
        borderRadius: 4,
        translateX: pos.x,
        translateY: pos.y,
        position: 'fixed',
        top: 0,
        left: 0,
        pointerEvents: 'none',
      }}
    />
  );
};

export default App;
`;

export const v5_x_x_gesture_useMove_MultipleElements = `import React, { createRef, useMemo, useState } from 'react';
import { animate, useValue, useMove } from 'react-ui-animate';

const App = () => {
  const [pos, setPos] = useValue({ x: 0, y: 0 });

  const refs = useMemo(
    () => Array.from({ length: 3 }, () => createRef<HTMLDivElement>()),
    []
  );

  useMove(refs, function ({ event }) {
    setPos({ x: event.clientX, y: event.clientY });
  });

  return (
    <>
      <animate.div
        style={{
          width: 50,
          height: 50,
          backgroundColor: 'teal',
          borderRadius: 4,
          translateX: pos.x,
          translateY: pos.y,
          position: 'fixed',
          top: 0,
          left: 0,
          pointerEvents: 'none',
        }}
      />

      {refs.map((r, i) => (
        <div
          key={i}
          ref={r}
          style={{
            width: 400,
            height: 60,
            backgroundColor: '#f1f1f1',
            borderRadius: 4,
            border: '1px solid #e1e1e1',
            marginBottom: 40,
          }}
        />
      ))}
    </>
  );
};

export default App;
`;

export const v5_x_x_gesture_useMove_SingleElements = `import React, { useRef } from 'react';
import { animate, useValue, useMove } from 'react-ui-animate';

const App = () => {
  const ref = useRef<HTMLDivElement>(null);
  const [pos, setPos] = useValue({ x: 0, y: 0 });

  useMove(ref, function ({ event }) {
    setPos({ x: event.clientX, y: event.clientY });
  });

  return (
    <>
      <animate.div
        style={{
          width: 50,
          height: 50,
          backgroundColor: 'teal',
          borderRadius: 4,
          translateX: pos.x,
          translateY: pos.y,
          position: 'fixed',
          top: 0,
          left: 0,
          pointerEvents: 'none',
        }}
      />

      <div
        ref={ref}
        style={{
          width: 300,
          height: 200,
          backgroundColor: '#f1f1f1',
          borderRadius: 4,
          border: '1px solid #e1e1e1',
        }}
      />
    </>
  );
};

export default App;
`;

export const v5_x_x_gesture_useScroll_BasicSetup = `import React, { useState } from 'react';
import { useScroll } from 'react-ui-animate';

const App = () => {
  const [scrollPosition, setScrollPosition] = useState(0);

  useScroll(window, function (event) {
    setScrollPosition(event.offset.y);
  });

  return (
    <div style={{ height: 2000 }}>
      <div style={{ position: 'fixed', left: 10, top: 10 }}>
        SCROLL POSITION: {scrollPosition}
      </div>
    </div>
  );
};

export default App;
`;

export const v5_x_x_gesture_useWheel_BasicSetup = `import React, { useState } from 'react';
import { useWheel } from 'react-ui-animate';

const App = () => {
  const [wheelPosition, setWheelPosition] = useState({ x: 0, y: 0 });

  useWheel(window, function (event) {
    setWheelPosition({ x: event.offset.x, y: event.offset.y });
  });

  return (
    <div style={{ height: 2000 }}>
      <div style={{ position: 'fixed', left: 10, top: 10 }}>
        WHEEL POSITION: {wheelPosition.x}, {wheelPosition.y}
      </div>
    </div>
  );
};

export default App;
`;

export const v5_x_x_hook_useInView_BasicExample = `import React, { useRef, useEffect } from 'react';
import { useInView, useValue, animate, withSpring } from 'react-ui-animate';

export default function App() {
  const ref = useRef(null);
  const isInView = useInView(ref, { threshold: 0.3 });
  const [opacity, setOpacity] = useValue(0);
  const [translateY, setTranslateY] = useValue(50);
  const [scale, setScale] = useValue(0.8);

  useEffect(() => {
    if (isInView) {
      setOpacity(withSpring(1));
      setTranslateY(withSpring(0));
      setScale(withSpring(1));
    } else {
      setOpacity(withSpring(0));
      setTranslateY(withSpring(50));
      setScale(withSpring(0.8));
    }
  }, [isInView]);

  return (
    <div style={{ height: 2000 }}>
      <div style={{ padding: 40, height: 800 }}>
        <h1>Scroll down to see the animation</h1>
        <p>The box below will animate when it enters the viewport</p>
      </div>

      <animate.div
        ref={ref}
        style={{
          padding: 40,
          background: isInView ? 'teal' : '#e1e1e1',
          borderRadius: 8,
          opacity,
          translateY,
          scale,
          color: 'white',
          fontWeight: 'bold',
          textAlign: 'center',
          transition: 'background 0.3s',
        }}
      >
        <h2>{isInView ? 'I am in view!' : 'Scroll to see me'}</h2>
        <p>Status: {isInView ? 'Visible' : 'Not Visible'}</p>
      </animate.div>

      <div style={{ height: 800, padding: 40 }}>
        <p>Keep scrolling...</p>
      </div>
    </div>
  );
}

`;

export const v5_x_x_hook_useInView_LazyLoadExample = `import React, { useRef, useEffect, useState } from 'react';
import { useInView } from 'react-ui-animate';

export default function App() {
  const ref = useRef(null);
  const isInView = useInView(ref, { threshold: 0.1 });
  const [imageSrc, setImageSrc] = useState<string | null>(null);

  useEffect(() => {
    if (isInView && !imageSrc) {
      // Simulate loading delay
      setTimeout(() => {
        setImageSrc('https://picsum.photos/800/400');
      }, 500);
    }
  }, [isInView, imageSrc]);

  return (
    <div style={{ height: 2000 }}>
      <div style={{ padding: 40, height: 800 }}>
        <h1>Lazy Loading Example</h1>
        <p>Scroll down to see the image load when it enters the viewport</p>
      </div>

      <div
        ref={ref}
        style={{
          minHeight: 400,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          background: '#f0f0f0',
          borderRadius: 8,
          margin: 40,
        }}
      >
        {imageSrc ? (
          <img
            src={imageSrc}
            alt="Lazy loaded"
            style={{
              width: '100%',
              maxWidth: 800,
              height: 'auto',
              borderRadius: 8,
            }}
          />
        ) : (
          <div
            style={{
              padding: 40,
              textAlign: 'center',
              color: '#666',
            }}
          >
            <div
              style={{
                width: 50,
                height: 50,
                border: '4px solid #e1e1e1',
                borderTop: '4px solid #667eea',
                borderRadius: '50%',
                animation: 'spin 1s linear infinite',
                margin: '0 auto 20px',
              }}
            />
            <p>Loading image...</p>
            <p style={{ fontSize: 12, marginTop: 10 }}>
              {isInView ? 'Image is in view, loading...' : 'Scroll to load'}
            </p>
          </div>
        )}
      </div>

      <div style={{ height: 800, padding: 40 }}>
        <p>Image loaded: {imageSrc ? 'Yes' : 'No'}</p>
      </div>

      <style>{\`
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      \`}</style>
    </div>
  );
}

`;

export const v5_x_x_hook_useOutsideClick_BasicExample = `import React, { useRef } from 'react';
import { useOutsideClick } from 'react-ui-animate';

export default function App() {
  const ref = useRef(null);

  useOutsideClick(ref, () => {
    alert('You clicked outside box');
  });

  return (
    <>
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          height: '100vh',
          alignItems: 'center',
        }}
      >
        <div
          style={{
            padding: 100,
            position: 'absolute',
            left: 0,
            top: 0,
            color: '#a1a1a1',
          }}
        >
          CLICK OUTSIDE
        </div>

        <div
          ref={ref}
          style={{
            width: 200,
            height: 200,
            border: '1px solid #e1e1e1',
            borderRadius: 8,
            backgroundColor: '#f1f1f1',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: '#a1a1a1',
            zIndex: 1,
          }}
        >
          CLICK INSIDE ME
        </div>
      </div>
    </>
  );
}
`;

export const v5_x_x_hook_useScrollProgress_BasicExample = `import React, { useRef } from 'react';
import { useScroll, animate } from 'react-ui-animate';

export default function App() {
  const { scrollYProgress } = useScroll(window);

  return (
    <div style={{ height: 3000 }}>
      <h1 style={{ padding: 40 }}>Scroll down to see progress</h1>
      
      {/* Progress Bar */}
      <animate.div
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          width: scrollYProgress.to([0, 1], ['0%', '100%']),
          height: 4,
          background: 'linear-gradient(90deg, #667eea, #764ba2)',
          zIndex: 1000,
        }}
      />

      {/* Animated Box */}
      <animate.div
        style={{
          position: 'fixed',
          top: '50%',
          left: '50%',
          translateX: -50,
          translateY: -50,
          width: 150,
          height: 150,
          scale: scrollYProgress.to([0, 1], [1, 1.5]),
          opacity: scrollYProgress.to([0, 0.5, 1], [1, 0.5, 1]),
          backgroundColor: scrollYProgress.to(
            [0, 1],
            ['#0069d9', '#ff5733']
          ),
          borderRadius: 8,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          color: 'white',
          fontWeight: 'bold',
        }}
      >
        {Math.round(scrollYProgress.get() * 100)}%
      </animate.div>

      <div style={{ height: 2000, padding: 40 }}>
        <p>Keep scrolling to see the progress change</p>
      </div>
    </div>
  );
}

`;

export const v5_x_x_hook_useScrollProgress_ElementProgress = `import React, { useRef } from 'react';
import { useScroll, animate } from 'react-ui-animate';

export default function App() {
  const containerRef = useRef(null);
  const { scrollYProgress } = useScroll(window, {
    target: containerRef,
    offset: ['start end', 'start start'],
  });

  return (
    <div style={{ height: 2000 }}>
      <div style={{ padding: 40, height: 600 }}>
        <h1>Element-Specific Progress</h1>
        <p>Scroll to see this element animate as it enters the viewport</p>
      </div>

      <animate.div
        ref={containerRef}
        style={{
          margin: 40,
          padding: 40,
          background: 'teal',
          borderRadius: 8,
          opacity: scrollYProgress.to([0, 1], [0, 1]),
          translateY: scrollYProgress.to([0, 1], [50, 0]),
          scale: scrollYProgress.to([0, 1], [0.9, 1]),
          color: 'white',
        }}
      >
        <h2>This element animates as you scroll</h2>
        <p>Progress: {Math.round(scrollYProgress.get() * 100)}%</p>
        <div
          style={{
            marginTop: 20,
            height: 4,
            background: 'rgba(255,255,255,0.3)',
            borderRadius: 2,
            overflow: 'hidden',
          }}
        >
          <animate.div
            style={{
              width: scrollYProgress.to([0, 1], ['0%', '100%']),
              height: '100%',
              background: 'white',
            }}
          />
        </div>
      </animate.div>

      <div style={{ height: 800, padding: 40 }}>
        <p>Keep scrolling...</p>
      </div>
    </div>
  );
}

`;

export const v5_x_x_modifier_withDecay_BasicExample = `import React from 'react';
import { useValue, animate, withDecay } from 'react-ui-animate';
import '../../styles.css';

export default function BasicExample() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() =>
          setObj(
            withDecay(0.3, {
              onStart: () => console.log('START'),
              onComplete: () => console.log('Animation complete'),
            })
          )
        }
      >
        Start
      </button>
      <button
        className="button buttonSecondary"
        onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}
      >
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          margin: '20px auto 0',
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 8,
        }}
      />
    </div>
  );
}
`;

export const v5_x_x_modifier_withLoop_BasicExample = `import React from 'react';
import {
  useValue,
  animate,
  withTiming,
  withSequence,
  withSpring,
  withDelay,
  withDecay,
  withLoop,
} from 'react-ui-animate';
import '../../styles.css';

export default function BasicExample() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() =>
          setObj(
            withLoop(
              withSequence([
                withTiming({ x: 100 }),
                withTiming({ y: 100 }),
                withTiming({ x: 0 }),
                withTiming({ y: 0 }),
              ]),
              5,
              {
                onStart() {
                  console.log('Loop started');
                },
                onComplete() {
                  console.log('Loop completed');
                },
              }
            )
          )
        }
      >
        Start
      </button>
      <button
        className="button buttonSecondary"
        onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}
      >
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          margin: '20px auto 0',
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 8,
        }}
      />
    </div>
  );
}
`;

export const v5_x_x_modifier_withSequence_BasicExample = `import React from 'react';
import {
  useValue,
  animate,
  withTiming,
  withSequence,
  withSpring,
  withDelay,
  withDecay,
} from 'react-ui-animate';
import '../../styles.css';

export default function BasicExample() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() =>
          setObj(
            withSequence(
              [
                withSpring({ x: 100, y: 100 }),
                withTiming({ width: 200, height: 200 }),
                withDelay(1000),
                withTiming({ x: 0, y: 0 }, { duration: 3000 }),
                withDecay(0.5),
              ],
              {
                onStart() {
                  console.log('obj sequence started');
                },
                onComplete() {
                  console.log('obj sequence completed');
                },
              }
            )
          )
        }
      >
        Start
      </button>
      <button
        className="button buttonSecondary"
        onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}
      >
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          margin: '20px auto 0',
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 8,
        }}
      />
    </div>
  );
}
`;

export const v5_x_x_modifier_withSpring_ArrayExample = `import React from 'react';
import { useValue, withSpring, animate } from 'react-ui-animate';
import '../../styles.css';

export default function App() {
  const [values, setValues] = useValue([0, 0, 0]);

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() => setValues(withSpring([10, 100, 200]))}
      >
        Start
      </button>
      <button
        className="button buttonSecondary"
        onClick={() => setValues([0, 0, 0])}
      >
        Reset
      </button>

      <div style={{ marginTop: 20, display: 'flex', gap: 10, justifyContent: 'center' }}>
        {values.map((value, index) => (
          <animate.div
            key={index}
            style={{
              width: 100,
              height: 100,
              backgroundColor: 'teal',
              translateX: value,
              borderRadius: 8,
            }}
          />
        ))}
      </div>
    </div>
  );
}
`;

export const v5_x_x_modifier_withSpring_GetStartedExample = `import React from 'react';
import { animate, useValue, withSpring } from 'react-ui-animate';
import './styles.css';

export default function App() {
  const [width, setWidth] = useValue(100);

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() => setWidth(withSpring(200))}
      >
        Expand
      </button>
      <button
        className="button buttonSecondary"
        onClick={() => setWidth(withSpring(100))}
      >
        Reset
      </button>
      <animate.div
        style={{
          width,
          height: 100,
          backgroundColor: 'teal',
          borderRadius: '8px',
          margin: '20px auto 0',
        }}
      />
    </div>
  );
}
`;

export const v5_x_x_modifier_withSpring_ObjectExample = `import React from 'react';
import { useValue, withSpring, animate } from 'react-ui-animate';
import '../../styles.css';

export default function App() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() =>
          setObj(
            withSpring(
              { x: 100, y: 100, width: 200, height: 200 },
              {
                onStart: () => console.log('START'),
                onComplete: () => console.log('Animation complete'),
              }
            )
          )
        }
      >
        Start
      </button>
      <button
        className="button buttonSecondary"
        onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}
      >
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          margin: '20px auto 0',
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 8,
        }}
      />
    </div>
  );
}
`;

export const v5_x_x_modifier_withSpring_PrimitiveExample = `import React from 'react';
import { animate, useValue, withSpring, withTiming } from 'react-ui-animate';
import '../../styles.css';

const App: React.FC = () => {
  const [bg, setBg] = useValue('teal');

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() => setBg(withSpring('blue'))}
      >
        Spring to Blue
      </button>
      <button
        className="button buttonPrimary"
        onClick={() => setBg(withSpring('purple'))}
      >
        Spring to Purple
      </button>
      <button
        className="button buttonPrimary"
        onClick={() => setBg(withTiming('red', { duration: 2000 }))}
      >
        Timing Red
      </button>
      <button
        className="button buttonSecondary"
        onClick={() => setBg('teal')}
      >
        Immediate to Teal
      </button>

      <animate.div
        style={{
          width: 100,
          height: 100,
          backgroundColor: bg,
          margin: '20px auto 0',
          borderRadius: 8,
        }}
      />
    </div>
  );
};

export default App;
`;

export const v5_x_x_modifier_withTiming_BasicExample = `import React from 'react';
import { useValue, animate, withTiming } from 'react-ui-animate';
import '../../styles.css';

export default function BasicExample() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <div className="container">
      <button
        className="button buttonPrimary"
        onClick={() =>
          setObj(
            withTiming(
              { x: 0, y: 0, width: 300, height: 100 },
              {
                duration: 400,
                onStart: () => console.log('START'),
                onComplete: () => console.log('Animation complete'),
              }
            )
          )
        }
      >
        Start
      </button>
      <button
        className="button buttonSecondary"
        onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}
      >
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          margin: '20px auto 0',
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 8,
        }}
      />
    </div>
  );
}
`;


export const sharedStyles = `/* Shared styles for all examples */

.container {
  padding: 2rem;
  text-align: center;
}

.button {
  padding: 12px 24px;
  font-size: 15px;
  font-weight: 600;
  color: white;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  margin-right: 12px;
  transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  position: relative;
  overflow: hidden;
  letter-spacing: 0.3px;
}

.button::before {
  content: '';
  position: absolute;
  top: 50%;
  left: 50%;
  width: 0;
  height: 0;
  border-radius: 50%;
  background: rgba(255, 255, 255, 0.2);
  transform: translate(-50%, -50%);
  transition: width 0.4s, height 0.4s;
}

.button:hover::before {
  width: 300px;
  height: 300px;
}

.button:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.button:active {
  transform: translateY(0);
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
}

.button:focus {
  outline: none;
  box-shadow: 0 0 0 3px rgba(0, 123, 255, 0.25);
}

.buttonPrimary {
  background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);
}

.buttonPrimary:hover {
  background: linear-gradient(135deg, #0056b3 0%, #004085 100%);
}

.buttonSecondary {
  background: linear-gradient(135deg, #6c757d 0%, #545b62 100%);
}

.buttonSecondary:hover {
  background: linear-gradient(135deg, #545b62 0%, #3d4146 100%);
}

`;
