// This file is auto-generated by scripts/generate-examples-index.js
// Do not edit this file manually
// Run "npm run generate:examples" to regenerate

export const v3_3_0_AnimatedValues_index = `import React from 'react';
import { animate, useAnimatedValue, withTiming } from 'react-ui-animate';

export default function () {
  const opacity = useAnimatedValue(1);

  return (
    <div style={{ padding: 20 }}>
      <animate.div
        style={{
          opacity: opacity.value,
          height: 100,
          width: 100,
          background: '#39F',
          borderRadius: 4,
        }}
      />
      <button onClick={() => (opacity.value = 0)}>Fade Out</button>
      <button onClick={() => (opacity.value = withTiming(1, { duration: 0 }))}>
        Reset
      </button>
    </div>
  );
}
`;

export const v3_3_0_AnimationModifiers_WithConfigModifier = `import React from 'react';

import {
  animate,
  AnimationConfigUtils,
  useAnimatedValue,
  withConfig,
} from 'react-ui-animate';

const WithConfigModifier = () => {
  const translateX = useAnimatedValue(0);

  return (
    <div style={{ padding: 20 }}>
      <animate.div
        style={{
          height: 100,
          width: 100,
          background: '#c370ff',
          borderRadius: 4,
          translateX: translateX.value,
        }}
      />

      <button
        onClick={() =>
          (translateX.value = withConfig(0, AnimationConfigUtils.WOOBLE))
        }
      >
        Animate Left
      </button>
      <button
        onClick={() => {
          translateX.value = withConfig(100, AnimationConfigUtils.BOUNCE);
        }}
      >
        Animate Right
      </button>
    </div>
  );
};

export default WithConfigModifier;
`;

export const v3_3_0_AnimationModifiers_WithEaseModifier = `import React from 'react';

import { animate, useAnimatedValue } from 'react-ui-animate';

const WithEaseModifier = () => {
  const translateX = useAnimatedValue(0);

  return (
    <div style={{ padding: 20 }}>
      <animate.div
        style={{
          height: 100,
          width: 100,
          background: '#32a852',
          borderRadius: 4,
          translateX: translateX.value,
        }}
      />

      <button onClick={() => (translateX.value = 100)}>Animate Right</button>
      <button
        onClick={() =>
          (translateX.value = { toValue: 0, config: { immediate: true } })
        }
      >
        Reset
      </button>
    </div>
  );
};

export default WithEaseModifier;
`;

export const v3_3_0_AnimationModifiers_WithSequenceModifier = `import React from 'react';

import {
  animate,
  useAnimatedValue,
  withSequence,
  withSpring,
  withTiming,
} from 'react-ui-animate';

const WithSequenceModifier = () => {
  const translateX = useAnimatedValue(0);

  return (
    <div style={{ padding: 20 }}>
      <animate.div
        style={{
          height: 100,
          width: 100,
          background: '#f0ca6c',
          borderRadius: 4,
          translateX: translateX.value,
        }}
      />

      <button
        onClick={() => {
          translateX.value = withSequence([withSpring(50), withTiming(100)]);
        }}
      >
        Animate Right
      </button>
      <button
        onClick={() =>
          (translateX.value = { toValue: 0, config: { immediate: true } })
        }
      >
        Reset
      </button>
    </div>
  );
};

export default WithSequenceModifier;
`;

export const v3_3_0_AnimationModifiers_WithSpringModifier = `import React from 'react';

import { animate, useAnimatedValue, withSpring } from 'react-ui-animate';

const WithSpringModifier = () => {
  const translateX = useAnimatedValue(0);

  return (
    <div style={{ padding: 20 }}>
      <animate.div
        style={{
          height: 100,
          width: 100,
          background: '#f5533d',
          borderRadius: 4,
          translateX: translateX.value,
        }}
      />

      <button onClick={() => (translateX.value = withSpring(100))}>
        Animate Right
      </button>
      <button
        onClick={() =>
          (translateX.value = { toValue: 0, config: { immediate: true } })
        }
      >
        Reset
      </button>
    </div>
  );
};

export default WithSpringModifier;
`;

export const v3_3_0_AnimationModifiers_WithSpringModifierConfig = `import React from 'react';

import { animate, useAnimatedValue, withSpring } from 'react-ui-animate';

const WithSpringModifierConfig = () => {
  const translateX = useAnimatedValue(0);

  return (
    <div style={{ padding: 20 }}>
      <animate.div
        style={{
          height: 100,
          width: 100,
          background: '#f5533d',
          borderRadius: 4,
          translateX: translateX.value,
        }}
      />

      <button
        onClick={() => (translateX.value = withSpring(100, { friction: 5 }))}
      >
        Animate Right
      </button>
      <button
        onClick={() =>
          (translateX.value = { toValue: 0, config: { immediate: true } })
        }
      >
        Reset
      </button>
    </div>
  );
};

export default WithSpringModifierConfig;
`;

export const v3_3_0_AnimationModifiers_WithTimingModifier = `import React from 'react';

import { animate, useAnimatedValue, withTiming } from 'react-ui-animate';

const WithTimingModifier = () => {
  const translateX = useAnimatedValue(0);

  return (
    <div style={{ padding: 20 }}>
      <animate.div
        style={{
          height: 100,
          width: 100,
          background: '#3399ff',
          borderRadius: 4,
          translateX: translateX.value,
        }}
      />

      <button onClick={() => (translateX.value = withTiming(100))}>
        Animate Right
      </button>
      <button
        onClick={() =>
          (translateX.value = { toValue: 0, config: { immediate: true } })
        }
      >
        Reset
      </button>
    </div>
  );
};

export default WithTimingModifier;
`;

export const v3_3_0_AnimationModifiers_WithTimingModifierConfig = `import React from 'react';

import { animate, useAnimatedValue, withTiming } from 'react-ui-animate';

const WithTimingModifierConfig = () => {
  const translateX = useAnimatedValue(0);

  return (
    <div style={{ padding: 20 }}>
      <animate.div
        style={{
          height: 100,
          width: 100,
          background: '#3399ff',
          borderRadius: 4,
          translateX: translateX.value,
        }}
      />

      <button
        onClick={() => (translateX.value = withTiming(100, { duration: 5000 }))}
      >
        Animate Right
      </button>
      <button
        onClick={() =>
          (translateX.value = { toValue: 0, config: { immediate: true } })
        }
      >
        Reset
      </button>
    </div>
  );
};

export default WithTimingModifierConfig;
`;

export const v3_3_0_ConfiguringAnimation_BounceAnimation = `import React from 'react';
import {
  animate,
  useAnimatedValue,
  AnimationConfigUtils,
} from 'react-ui-animate';

const BounceAnimation = () => {
  const left = useAnimatedValue(0, AnimationConfigUtils.BOUNCE);

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      <animate.div
        style={{
          width: 100,
          height: 100,
          backgroundColor: '#3399ff',
          borderRadius: 4,
          position: 'relative',
          left: left.value,
        }}
      />

      <button onClick={() => (left.value = 0)}>Left</button>
      <button onClick={() => (left.value = 200)}>Right</button>
    </div>
  );
};

export default BounceAnimation;
`;

export const v3_3_0_ConfiguringAnimation_CubicBezierAnimation = `import React from 'react';
import { animate, useAnimatedValue, Easing } from 'react-ui-animate';

const CubicBezierAnimation = () => {
  const left = useAnimatedValue(0, {
    duration: 1000,
    easing: Easing.bezier(0.17, 0.67, 0.83, 0.67),
  });

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      <animate.div
        style={{
          width: 100,
          height: 100,
          backgroundColor: '#3399ff',
          borderRadius: 4,
          position: 'relative',
          left: left.value,
        }}
      />

      <button onClick={() => (left.value = 0)}>Left</button>
      <button onClick={() => (left.value = 200)}>Right</button>
    </div>
  );
};

export default CubicBezierAnimation;
`;

export const v3_3_0_ConfiguringAnimation_SpringAnimation = `import React from 'react';
import { animate, useAnimatedValue } from 'react-ui-animate';

const SpringAnimation = () => {
  const left = useAnimatedValue(0, { mass: 1, friction: 10, tension: 200 });

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      <animate.div
        style={{
          width: 100,
          height: 100,
          backgroundColor: '#3399ff',
          borderRadius: 4,
          position: 'relative',
          left: left.value,
        }}
      />

      <button onClick={() => (left.value = 0)}>Left</button>
      <button onClick={() => (left.value = 200)}>Right</button>
    </div>
  );
};

export default SpringAnimation;
`;

export const v3_3_0_ConfiguringAnimation_TimingAnimation = `import React from 'react';
import { animate, useAnimatedValue } from 'react-ui-animate';

const TimingAnimation = () => {
  const left = useAnimatedValue(0, { duration: 1000 });

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      <animate.div
        style={{
          width: 100,
          height: 100,
          backgroundColor: '#3399ff',
          borderRadius: 4,
          position: 'relative',
          left: left.value,
        }}
      />

      <button onClick={() => (left.value = 0)}>Left</button>
      <button onClick={() => (left.value = 200)}>Right</button>
    </div>
  );
};

export default TimingAnimation;
`;

export const v3_3_0_Gestures_index = `import React from 'react';
import { animate, useAnimatedValue, useDrag } from 'react-ui-animate';

const DragGesture = () => {
  const left = useAnimatedValue(0);

  const bind = useDrag(({ down, movementX }) => {
    left.value = down ? movementX : 0;
  });

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      <animate.div
        {...bind()}
        style={{
          width: 100,
          height: 100,
          backgroundColor: '#f5533d',
          borderRadius: 4,
          position: 'relative',
          left: left.value,
        }}
      />
    </div>
  );
};

export default DragGesture;
`;

export const v3_3_0_GettingStartedExamples_index = `import React from 'react';
import { animate, useAnimatedValue } from 'react-ui-animate';

const Example = () => {
  const left = useAnimatedValue(0);

  return (
    <div>
      <animate.div
        style={{
          width: 100,
          height: 100,
          background: '#39F',
          position: 'relative',
          left: left.value,
          borderRadius: 4,
        }}
      />

      <button onClick={() => (left.value = 0)}>Animate Left</button>
      <button onClick={() => (left.value = 200)}>Animate Right</button>
    </div>
  );
};

export default Example;
`;

export const v3_3_0_HomepageExamples_Gesture = `import React from 'react';
import {
  animate,
  useAnimatedValue,
  useDrag,
  withSpring,
} from 'react-ui-animate';

const Gesture = () => {
  const x = useAnimatedValue(0);
  const y = useAnimatedValue(0);

  const bind = useDrag(({ down, movementX, movementY }) => {
    x.value = down ? movementX : withSpring(0);
    y.value = down ? movementY : withSpring(0);
  });

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      <animate.div
        {...bind()}
        style={{
          width: 100,
          height: 100,
          backgroundColor: '#f5533d',
          borderRadius: 4,
          translateX: x.value,
          translateY: y.value,
          cursor: 'grabbing',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          margin: '0px auto',
          color: 'white',
          position: 'relative',
          zIndex: 1,
        }}
      >
        DRAG ME
      </animate.div>
    </div>
  );
};

export default Gesture;
`;

export const v3_3_0_HomepageExamples_HomepageExamples = `import React, { useState } from 'react';
import { Paper, Button, ButtonGroup } from '@mui/material';
import {
  animate,
  useAnimatedValue,
  interpolate,
  AnimationConfigUtils,
  useMountedValue,
} from 'react-ui-animate';

import styles from './index.module.css';
import Gesture from './Gesture';

const Unmounting = () => {
  const [visible, setVisible] = useState(true);

  const open = useMountedValue(visible, {
    from: 0,
    enter: 1,
    exit: 0,
  });

  return (
    <Paper
      variant="outlined"
      style={{
        padding: 20,
        marginBottom: 20,
      }}
    >
      {open(
        (animation, mounted) =>
          mounted && (
            <animate.div
              style={{
                width: 200,
                height: 100,
                backgroundColor: '#31915f',
                borderRadius: 4,
                opacity: animation.value,
                margin: 'auto',
                marginBottom: 10,
              }}
            />
          )
      )}

      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
        }}
      >
        <Button variant="outlined" onClick={() => setVisible(!visible)}>
          {visible ? 'Hide Element' : 'Show Element'}
        </Button>
      </div>
    </Paper>
  );
};

const AnimatedTransitionExample = () => {
  const left = useAnimatedValue(0, AnimationConfigUtils?.ELASTIC);

  return (
    <Paper variant="outlined" style={{ padding: 20, marginBottom: 20 }}>
      <animate.div
        style={{
          height: 100,
          background: '#39F',
          position: 'relative',
          left: left.value,
          borderRadius: 4,
          rotate: interpolate(left.value, [0, 200], [0, 180]),
          width: interpolate(left.value, [0, 200], [100, 200]),
          marginBottom: 10,
        }}
      />

      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
        }}
      >
        <ButtonGroup variant="outlined" aria-label="outlined button group">
          <Button onClick={() => (left.value = 0)}>Animate Left</Button>
          <Button onClick={() => (left.value = 200)}>Animate Right</Button>
        </ButtonGroup>
      </div>
    </Paper>
  );
};

const HomepageExamples = () => {
  return (
    <>
      <div style={{ borderTop: '1px solid #f1f1f1', marginTop: 40 }} />

      <section className={styles.container}>
        <div>
          <h2 className={styles.heading}>Animated Transition</h2>
          <h4 className={styles.subheading}>Animate from point a to point b</h4>
          <AnimatedTransitionExample />
        </div>

        <div>
          <h2 className={styles.heading}>Gestures</h2>
          <h4 className={styles.subheading}>
            Handle complex gestures according to your need
          </h4>
          <Gesture />
        </div>

        <div>
          <h2 className={styles.heading}>Mounting / Unmounting Transition</h2>
          <h4 className={styles.subheading}>
            Control the animation for mounting / unmouting component from the
            DOM
          </h4>
          <Unmounting />
        </div>
      </section>
    </>
  );
};

export default HomepageExamples;
`;

export const v3_3_0_HomepageFeatures_index = `import React from 'react';
import clsx from 'clsx';
import { FaHandHoldingHeart } from 'react-icons/fa';
import { MdDraw } from 'react-icons/md';
import { PiHandTapFill } from 'react-icons/pi';

const FeatureList = [
  {
    title: 'Easy to Use',
    icon: <FaHandHoldingHeart size={60} />,
    description: (
      <>
        React UI Animate offers intuitive APIs that simplify implementing
        animations and gestures in your projects.
      </>
    ),
  },
  {
    title: 'Animate Anything',
    icon: <MdDraw size={60} />,
    description: (
      <>
        With React UI Animate, you can create beautiful animations for any
        element effortlessly.
      </>
    ),
  },
  {
    title: 'Engage with Interactive Elements',
    icon: <PiHandTapFill size={60} />,
    description: (
      <>
        React UI Animate provides a variety of APIs to easily implement complex
        gestures, enhancing user interaction.
      </>
    ),
  },
];

function Feature({ icon, title, description }) {
  return (
    <div className={clsx('col col--4')}>
      <div className="text--center">{icon}</div>
      <div className="text--center padding-horiz--md">
        <h3>{title}</h3>
        <p>{description}</p>
      </div>
    </div>
  );
}

export default function HomepageFeatures() {
  return (
    <section
      style={{
        display: 'flex',
        alignItems: 'center',
        padding: '2rem 0',
        width: '100%',
      }}
    >
      <div className="container">
        <div className="row">
          {FeatureList.map((props, idx) => (
            <Feature key={idx} {...props} />
          ))}
        </div>
      </div>
    </section>
  );
}
`;

export const v3_3_0_Interpolation_example1 = `import React from 'react';
import {
  animate,
  useAnimatedValue,
  interpolate,
  withTiming,
} from 'react-ui-animate';

const Example = () => {
  const left = useAnimatedValue(0);

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      <animate.div
        style={{
          width: interpolate(left.value, [0, 200], [100, 400]),
          height: 100,
          backgroundColor: '#3399ff',
          borderRadius: 4,
          position: 'relative',
          left: left.value,
        }}
      />

      <button onClick={() => (left.value = 200)}>Animate</button>
      <button onClick={() => (left.value = withTiming(0, { duration: 0 }))}>
        Reset
      </button>
    </div>
  );
};

export default Example;
`;

export const v3_3_0_Interpolation_example2 = `import React from 'react';
import {
  animate,
  useAnimatedValue,
  interpolate,
  withTiming,
} from 'react-ui-animate';

const Example = () => {
  const opacity = useAnimatedValue(0);

  return (
    <div>
      <animate.div
        style={{
          width: 100,
          height: 100,
          backgroundColor: interpolate(opacity.value, [0, 1], ['red', 'black']),
          borderRadius: 4,
        }}
      />

      <button onClick={() => (opacity.value = 1)}>Animate</button>
      <button onClick={() => (opacity.value = withTiming(0, { duration: 0 }))}>
        Reset
      </button>
    </div>
  );
};

export default Example;
`;

export const v3_3_0_Unmounting_ConfigureUnmounting = `import React, { useState } from 'react';
import {
  animate,
  useMountedValue,
  interpolate,
  AnimationConfigUtils,
} from 'react-ui-animate';

const ConfigureUnmounting = () => {
  const [visible, setVisible] = useState(false);

  const open = useMountedValue(visible, {
    from: 0,
    enter: 1,
    exit: 0,
    config: AnimationConfigUtils.BOUNCE,
  });

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      {open(
        (animation, mounted) =>
          mounted && (
            <animate.div
              style={{
                width: 100,
                height: 100,
                backgroundColor: '#3399ff',
                borderRadius: 4,
                opacity: animation.value,
                marginBottom: 10,
                position: 'relative',
                left: interpolate(animation.value, [0, 1], [0, 200]),
              }}
            />
          )
      )}

      <button onClick={() => setVisible(!visible)}>
        {visible ? 'Hide' : 'Show'}
      </button>
    </div>
  );
};

export default ConfigureUnmounting;
`;

export const v3_3_0_Unmounting_Unmounting = `import React, { useState } from 'react';
import { animate, useMountedValue } from 'react-ui-animate';

const Unmounting = () => {
  const [visible, setVisible] = useState(true);

  const open = useMountedValue(visible, {
    from: 0,
    enter: 1,
    exit: 0,
  });

  return (
    <div style={{ padding: 20, marginBottom: 20 }}>
      {open(
        (animation, mounted) =>
          mounted && (
            <animate.div
              style={{
                width: 100,
                height: 100,
                backgroundColor: '#31915f',
                borderRadius: 4,
                opacity: animation.value,
                marginBottom: 10,
              }}
            />
          )
      )}

      <button onClick={() => setVisible(!visible)}>
        {visible ? 'Hide' : 'Show'}
      </button>
    </div>
  );
};

export default Unmounting;
`;

export const v5_x_x_core_interpolation_BasicExample = `import React from 'react';
import { useValue, animate, withSpring } from 'react-ui-animate';

export default function App() {
  const [x, setX] = useValue(0);

  return (
    <>
      <button onClick={() => setX(withSpring(200))}>Animate</button>

      <animate.div
        style={{
          marginTop: 10,
          width: 100,
          height: 100,
          background: x.to([0, 200], ['teal', 'red']),
          translateX: x,
          borderRadius: 4,
        }}
      />
    </>
  );
}
`;

export const v5_x_x_core_mount_BasicExample = `import React from 'react';
import { animate, Mount } from 'react-ui-animate';

const App = () => {
  const [open, setOpen] = React.useState(true);

  return (
    <>
      <Mount state={open}>
        {(animation) => (
          <animate.div
            style={{
              width: 100,
              height: 100,
              backgroundColor: 'teal',
              opacity: animation,
              borderRadius: 4,
              marginBottom: 10,
            }}
          />
        )}
      </Mount>

      <button
        onClick={() => {
          setOpen((prev) => !prev);
        }}
      >
        ANIMATE
      </button>
    </>
  );
};

export default App;
`;

export const v5_x_x_core_mount_MultiValuedExample = `import React from 'react';
import {
  animate,
  withSequence,
  withTiming,
  withSpring,
  Mount,
} from 'react-ui-animate';

const App = () => {
  const [open, setOpen] = React.useState(true);

  return (
    <>
      <Mount
        state={open}
        from={{ width: 200, opacity: 0, translateX: 0, rotate: 0 }}
        enter={withSequence([
          withTiming({ translateX: 100, opacity: 1, rotate: 0 }),
          withSpring({ width: 300 }),
        ])}
        exit={withSpring({
          translateX: 0,
          width: 200,
        })}
      >
        {({ width, opacity, translateX, rotate }) => (
          <animate.div
            style={{
              width: width,
              opacity,
              translateX,
              height: 100,
              backgroundColor: 'teal',
              rotate,
              borderRadius: 4,
              marginBottom: 10,
            }}
          />
        )}
      </Mount>

      <button
        onClick={() => {
          setOpen((prev) => !prev);
        }}
      >
        ANIMATE ME
      </button>
    </>
  );
};

export default App;
`;

export const v5_x_x_gesture_useDrag_BasicSetup = `import React, { useRef } from 'react';
import { animate, useDrag, useValue, withSpring } from 'react-ui-animate';

const App = () => {
  const ref = useRef<HTMLDivElement>(null);
  const [translateX, setTranslateX] = useValue(0);
  const [translateY, setTranslateY] = useValue(0);

  useDrag(ref, ({ down, movement }) => {
    setTranslateX(down ? movement.x : withSpring(0));
    setTranslateY(down ? movement.y : withSpring(0));
  });

  return (
    <animate.div
      ref={ref}
      style={{
        cursor: 'grab',
        translateX,
        translateY,
        width: 100,
        height: 100,
        backgroundColor: 'teal',
        borderRadius: 4,
      }}
    />
  );
};

export default App;
`;

export const v5_x_x_gesture_useDrag_MultipleElements = `import React, { createRef, useMemo, useRef } from 'react';
import { animate, useValue, useDrag, withSpring } from 'react-ui-animate';

const App = () => {
  const items = useRef(Array.from({ length: 5 }, () => 0));
  const [positions, setPositions] = useValue(items.current);

  const refs = useMemo(
    () => Array.from({ length: 3 }, () => createRef<HTMLDivElement>()),
    []
  );

  useDrag(refs, function ({ down, movement, index }) {
    if (down) {
      const newPositions = [...items.current];
      newPositions[index] = movement.x;
      setPositions(newPositions);
    } else {
      setPositions(withSpring(items.current));
    }
  });

  return (
    <>
      {refs.map((r, i) => (
        <animate.div
          key={i}
          ref={r}
          style={{
            width: 100,
            height: 100,
            cursor: 'grab',
            backgroundColor: 'teal',
            borderRadius: 4,
            marginBottom: 10,
            translateX: positions[i],
          }}
        />
      ))}
    </>
  );
};

export default App;
`;

export const v5_x_x_gesture_useMove_BasicSetup = `import React from 'react';
import { animate, useValue, useMove } from 'react-ui-animate';

const App = () => {
  const [pos, setPos] = useValue({ x: 0, y: 0 });

  useMove(window, function ({ event }) {
    setPos({ x: event.clientX, y: event.clientY });
  });

  return (
    <animate.div
      style={{
        width: 50,
        height: 50,
        backgroundColor: 'teal',
        borderRadius: 4,
        translateX: pos.x,
        translateY: pos.y,
        position: 'fixed',
        top: 0,
        left: 0,
        pointerEvents: 'none',
      }}
    />
  );
};

export default App;
`;

export const v5_x_x_gesture_useMove_MultipleElements = `import React, { createRef, useMemo, useState } from 'react';
import { animate, useValue, useMove } from 'react-ui-animate';

const App = () => {
  const [pos, setPos] = useValue({ x: 0, y: 0 });

  const refs = useMemo(
    () => Array.from({ length: 3 }, () => createRef<HTMLDivElement>()),
    []
  );

  useMove(refs, function ({ event }) {
    setPos({ x: event.clientX, y: event.clientY });
  });

  return (
    <>
      <animate.div
        style={{
          width: 50,
          height: 50,
          backgroundColor: 'teal',
          borderRadius: 4,
          translateX: pos.x,
          translateY: pos.y,
          position: 'fixed',
          top: 0,
          left: 0,
          pointerEvents: 'none',
        }}
      />

      {refs.map((r, i) => (
        <div
          key={i}
          ref={r}
          style={{
            width: 400,
            height: 60,
            backgroundColor: '#f1f1f1',
            borderRadius: 4,
            border: '1px solid #e1e1e1',
            marginBottom: 40,
          }}
        />
      ))}
    </>
  );
};

export default App;
`;

export const v5_x_x_gesture_useMove_SingleElements = `import React, { useRef } from 'react';
import { animate, useValue, useMove } from 'react-ui-animate';

const App = () => {
  const ref = useRef<HTMLDivElement>(null);
  const [pos, setPos] = useValue({ x: 0, y: 0 });

  useMove(ref, function ({ event }) {
    setPos({ x: event.clientX, y: event.clientY });
  });

  return (
    <>
      <animate.div
        style={{
          width: 50,
          height: 50,
          backgroundColor: 'teal',
          borderRadius: 4,
          translateX: pos.x,
          translateY: pos.y,
          position: 'fixed',
          top: 0,
          left: 0,
          pointerEvents: 'none',
        }}
      />

      <div
        ref={ref}
        style={{
          width: 300,
          height: 200,
          backgroundColor: '#f1f1f1',
          borderRadius: 4,
          border: '1px solid #e1e1e1',
        }}
      />
    </>
  );
};

export default App;
`;

export const v5_x_x_gesture_useScroll_BasicSetup = `import React, { useState } from 'react';
import { useScroll } from 'react-ui-animate';

const App = () => {
  const [scrollPosition, setScrollPosition] = useState(0);

  useScroll(window, function (event) {
    setScrollPosition(event.offset.y);
  });

  return (
    <div style={{ height: 2000 }}>
      <div style={{ position: 'fixed', left: 10, top: 10 }}>
        SCROLL POSITION: {scrollPosition}
      </div>
    </div>
  );
};

export default App;
`;

export const v5_x_x_gesture_useWheel_BasicSetup = `import React, { useState } from 'react';
import { useWheel } from 'react-ui-animate';

const App = () => {
  const [wheelPosition, setWheelPosition] = useState({ x: 0, y: 0 });

  useWheel(window, function (event) {
    setWheelPosition({ x: event.offset.x, y: event.offset.y });
  });

  return (
    <div style={{ height: 2000 }}>
      <div style={{ position: 'fixed', left: 10, top: 10 }}>
        WHEEL POSITION: {wheelPosition.x}, {wheelPosition.y}
      </div>
    </div>
  );
};

export default App;
`;

export const v5_x_x_hook_useOutsideClick_BasicExample = `import React, { useRef } from 'react';
import { useOutsideClick } from 'react-ui-animate';

export default function App() {
  const ref = useRef(null);

  useOutsideClick(ref, () => {
    alert('You clicked outside box');
  });

  return (
    <>
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          height: '100vh',
          alignItems: 'center',
        }}
      >
        <div
          style={{
            padding: 100,
            position: 'absolute',
            left: 0,
            top: 0,
            color: '#a1a1a1',
          }}
        >
          CLICK OUTSIDE
        </div>

        <div
          ref={ref}
          style={{
            width: 200,
            height: 200,
            border: '1px solid #e1e1e1',
            borderRadius: 8,
            backgroundColor: '#f1f1f1',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: '#a1a1a1',
            zIndex: 1,
          }}
        >
          CLICK INSIDE ME
        </div>
      </div>
    </>
  );
}
`;

export const v5_x_x_modifier_withDecay_BasicExample = `import React from 'react';
import { useValue, animate, withDecay } from 'react-ui-animate';

export default function BasicExample() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <>
      <button
        onClick={() =>
          setObj(
            withDecay(0.3, {
              onStart: () => console.log('START'),
              onComplete: () => console.log('Animation complete'),
            })
          )
        }
      >
        Start
      </button>
      <button onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}>
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          left: 0,
          top: 0,
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 4,
        }}
      />
    </>
  );
}
`;

export const v5_x_x_modifier_withLoop_BasicExample = `import React from 'react';
import {
  useValue,
  animate,
  withTiming,
  withSequence,
  withSpring,
  withDelay,
  withDecay,
  withLoop,
} from 'react-ui-animate';

export default function BasicExample() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <>
      <button
        onClick={() =>
          setObj(
            withLoop(
              withSequence([
                withTiming({ x: 100 }),
                withTiming({ y: 100 }),
                withTiming({ x: 0 }),
                withTiming({ y: 0 }),
              ]),
              5,
              {
                onStart() {
                  console.log('Loop started');
                },
                onComplete() {
                  console.log('Loop completed');
                },
              }
            )
          )
        }
      >
        Start
      </button>
      <button onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}>
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          left: 0,
          top: 0,
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 4,
        }}
      />
    </>
  );
}
`;

export const v5_x_x_modifier_withSequence_BasicExample = `import React from 'react';
import {
  useValue,
  animate,
  withTiming,
  withSequence,
  withSpring,
  withDelay,
  withDecay,
} from 'react-ui-animate';

export default function BasicExample() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <>
      <button
        onClick={() =>
          setObj(
            withSequence(
              [
                withSpring({ x: 100, y: 100 }),
                withTiming({ width: 200, height: 200 }),
                withDelay(1000),
                withTiming({ x: 0, y: 0 }, { duration: 3000 }),
                withDecay(0.5),
              ],
              {
                onStart() {
                  console.log('obj sequence started');
                },
                onComplete() {
                  console.log('obj sequence completed');
                },
              }
            )
          )
        }
      >
        Start
      </button>
      <button onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}>
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          left: 0,
          top: 0,
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 4,
        }}
      />
    </>
  );
}
`;

export const v5_x_x_modifier_withSpring_ArrayExample = `import React from 'react';
import { useValue, withSpring, animate } from 'react-ui-animate';

export default function App() {
  const [values, setValues] = useValue([0, 0, 0]);

  return (
    <>
      <button onClick={() => setValues(withSpring([10, 100, 200]))}>
        Start
      </button>
      <button onClick={() => setValues([0, 0, 0])}>Reset</button>

      {values.map((value, index) => (
        <animate.div
          key={index}
          style={{
            width: 100,
            height: 100,
            backgroundColor: 'teal',
            left: 0,
            top: 0,
            translateX: value,
            borderRadius: 4,
          }}
        />
      ))}
    </>
  );
}
`;

export const v5_x_x_modifier_withSpring_GetStartedExample = `import React from 'react';
import { animate, useValue, withSpring, withTiming } from 'react-ui-animate';

export default function App() {
  const [width, setWidth] = useValue(100);

  return (
    <>
      <button onClick={() => setWidth(withSpring(200))}>Animate</button>
      <button onClick={() => setWidth(withTiming(100))}>Reset</button>
      <animate.div
        style={{
          width,
          marginTop: 10,
          height: 100,
          backgroundColor: 'teal',
          borderRadius: 4,
        }}
      />
    </>
  );
}
`;

export const v5_x_x_modifier_withSpring_ObjectExample = `import React from 'react';
import { useValue, withSpring, animate } from 'react-ui-animate';

export default function App() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <>
      <button
        onClick={() =>
          setObj(
            withSpring(
              { x: 100, y: 100, width: 200, height: 200 },
              {
                onStart: () => console.log('START'),
                onComplete: () => console.log('Animation complete'),
              }
            )
          )
        }
      >
        Start
      </button>
      <button onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}>
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          left: 0,
          top: 0,
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 4,
        }}
      />
    </>
  );
}
`;

export const v5_x_x_modifier_withSpring_PrimitiveExample = `import React from 'react';
import { animate, useValue, withSpring, withTiming } from 'react-ui-animate';

const App: React.FC = () => {
  const [bg, setBg] = useValue('teal');

  return (
    <>
      <button onClick={() => setBg(withSpring('blue'))}>Spring to Blue</button>
      <button onClick={() => setBg(withSpring('purple'))}>
        Spring to Purple
      </button>
      <button onClick={() => setBg(withTiming('red', { duration: 2000 }))}>
        Timing Red
      </button>
      <button onClick={() => setBg('teal')}>Immediate to Teal</button>

      <animate.div
        style={{
          width: 100,
          height: 100,
          backgroundColor: bg,
          left: 0,
          top: 0,
          borderRadius: 4,
        }}
      />
    </>
  );
};

export default App;
`;

export const v5_x_x_modifier_withTiming_BasicExample = `import React from 'react';
import { useValue, animate, withTiming } from 'react-ui-animate';

export default function BasicExample() {
  const [obj, setObj] = useValue({ x: 0, y: 0, width: 100, height: 100 });

  return (
    <>
      <button
        onClick={() =>
          setObj(
            withTiming(
              { x: 0, y: 0, width: 300, height: 100 },
              {
                duration: 400,
                onStart: () => console.log('START'),
                onComplete: () => console.log('Animation complete'),
              }
            )
          )
        }
      >
        Start
      </button>
      <button onClick={() => setObj({ x: 0, y: 0, width: 100, height: 100 })}>
        Reset
      </button>

      <animate.div
        style={{
          width: obj.width,
          height: 100,
          backgroundColor: 'teal',
          left: 0,
          top: 0,
          translateX: obj.x,
          translateY: obj.y,
          borderRadius: 4,
        }}
      />
    </>
  );
}
`;
